//! Self-contained embedding of the bundled Scheme deps.
//!
//! At build time `build.rs` embeds every `*.scm` under `deps/` as
//! [`DEPS_FILES`]. At runtime [`materialize`] writes them once to a persistent
//! cache dir (XDG `~/.cache/mr-guile-lsp/<version>/`) so a `guile -L <dir>`
//! subprocess can load the `(mr-guile-lsp …)` modules. Extraction happens only
//! once per version; subsequent launches reuse the cached tree.

use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};

/// Per-call counter so concurrent extractions in one process get unique staging
/// dirs (the PID alone collides for same-process parallel callers).
static STAGING_COUNTER: AtomicU64 = AtomicU64::new(0);

// Generated by build.rs (see OUT_DIR/deps_files.rs).
include!(concat!(env!("OUT_DIR"), "/deps_files.rs"));

/// Bumped into the cache path so a new release re-extracts fresh files.
const VERSION: &str = env!("CARGO_PKG_VERSION");
/// Written after a complete extraction so a partial tree is never reused.
const MARKER: &str = ".extracted";

/// Materialize the bundled deps into the persistent cache and return the dir.
/// Honors `$MR_GUILE_LSP_CACHE_DIR`, then `$XDG_CACHE_HOME`, then `~/.cache`.
/// This is the `--extract-deps` CLI path: it FORCES a fresh release — any
/// existing extraction is cleared first, so embedded-deps changes take effect
/// even when the version number didn't bump. Call this only from the CLI, not
/// from the server's hot path (the server reuses the cache via
/// [`materialized_dir`]).
pub fn materialize() -> std::io::Result<PathBuf> {
    materialize_force_into(&cache_base())
}

/// Force-extract into `base/<version>/`, clearing any stale tree first.
pub fn materialize_force_into(base: &Path) -> std::io::Result<PathBuf> {
    let target = base.join(VERSION);
    if target.exists() {
        std::fs::remove_dir_all(&target)?;
    }
    materialize_into(base)
}

/// Return the already-extracted cache dir, or `None` if not yet extracted.
/// Does NOT extract — the running server expects `--extract-deps` to have been
/// run once after install (manual release), and degrades gracefully if not.
pub fn materialized_dir() -> Option<PathBuf> {
    materialized_dir_in(&cache_base())
}

/// Same as [`materialized_dir`] but with an explicit base dir (for testing).
pub fn materialized_dir_in(base: &Path) -> Option<PathBuf> {
    let dir = base.join(VERSION);
    if dir.join(MARKER).exists() {
        Some(dir)
    } else {
        None
    }
}

/// Resolve the cache base directory (without the version segment).
fn cache_base() -> PathBuf {
    if let Ok(dir) = std::env::var("MR_GUILE_LSP_CACHE_DIR") {
        return PathBuf::from(dir);
    }
    if let Ok(dir) = std::env::var("XDG_CACHE_HOME") {
        return PathBuf::from(dir).join("mr-guile-lsp");
    }
    let home = std::env::var("HOME").unwrap_or_default();
    PathBuf::from(home).join(".cache").join("mr-guile-lsp")
}

/// Extract into `base/<version>/`, reusing an existing complete tree. The
/// extraction is made atomic by writing to a per-PID temp sibling and renaming.
pub fn materialize_into(base: &Path) -> std::io::Result<PathBuf> {
    let target = base.join(VERSION);
    if target.join(MARKER).exists() {
        return Ok(target);
    }

    let staging = base.join(format!(
        "{}.tmp-{}-{}",
        VERSION,
        std::process::id(),
        STAGING_COUNTER.fetch_add(1, Ordering::Relaxed)
    ));
    if staging.exists() {
        let _ = std::fs::remove_dir_all(&staging);
    }
    for (rel, content) in DEPS_FILES {
        let path = staging.join(rel);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&path, content)?;
    }
    std::fs::write(staging.join(MARKER), VERSION)?;

    // Atomic publish (rename overwrites an empty target; fails if non-empty).
    match std::fs::rename(&staging, &target) {
        Ok(()) => Ok(target),
        Err(_) => {
            // Likely a concurrent launch won the race — reuse its tree if ready.
            let _ = std::fs::remove_dir_all(&staging);
            if target.join(MARKER).exists() {
                Ok(target)
            } else {
                Err(std::io::Error::other(
                    "deps cache extraction lost a race and the target is incomplete",
                ))
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::guile::GuileRepl;
    use crate::parser::SExpr;
    use tempfile::TempDir;

    #[tokio::test]
    async fn materialized_bundle_is_loadable_by_guile() {
        // Use an isolated base so the test never touches the real user cache.
        let tmp = TempDir::new().expect("temp dir");
        let dir = materialize_into(tmp.path()).expect("materialize bundled deps");
        assert!(dir.join("mr-guile-lsp/geiser/completion.scm").exists());
        assert!(dir.join("mr-guile-lsp/lsp-helpers.scm").exists());

        let mut repl = GuileRepl::spawn(&dir).await.expect("spawn from bundle");
        let result = repl
            .request(r#"(lsp-completions "display")"#)
            .await
            .expect("completion via bundle");
        assert!(matches!(result, SExpr::List(_)), "got {result:?}");
    }

    #[test]
    fn extract_once_reuses_existing_tree() {
        let tmp = TempDir::new().expect("temp dir");
        let first = materialize_into(tmp.path()).expect("first extract");
        // Plant a sentinel; a re-extraction (rename) would wipe it.
        std::fs::write(first.join("sentinel-from-first-run"), "1").unwrap();

        let second = materialize_into(tmp.path()).expect("second extract");
        assert_eq!(first, second, "should return the same path");
        assert!(
            second.join("sentinel-from-first-run").exists(),
            "second call must not re-extract / wipe the existing tree"
        );
        assert!(second.join(MARKER).exists(), "marker must be present");
    }

    #[test]
    fn version_is_part_of_the_path() {
        // So a new release re-extracts fresh files instead of reusing stale ones.
        let tmp = TempDir::new().expect("temp dir");
        let dir = materialize_into(tmp.path()).expect("extract");
        assert!(
            dir.ends_with(VERSION),
            "cache path {dir:?} should end with the version {VERSION:?}"
        );
    }

    #[test]
    fn materialized_dir_is_none_before_extraction_then_some_after() {
        let tmp = TempDir::new().expect("temp dir");
        assert!(
            materialized_dir_in(tmp.path()).is_none(),
            "should be absent before extract"
        );
        materialize_into(tmp.path()).expect("extract");
        assert_eq!(
            materialized_dir_in(tmp.path()),
            Some(tmp.path().join(VERSION))
        );
    }

    #[test]
    fn force_extract_clears_stale_files_first() {
        let tmp = TempDir::new().expect("temp dir");
        // First extract, then plant a sentinel representing stale content.
        let dir = materialize_into(tmp.path()).expect("first extract");
        std::fs::write(dir.join("stale-sentinel"), "old").expect("plant sentinel");
        assert!(dir.join("stale-sentinel").exists());

        // Force extract (the --extract-deps path) must wipe stale files and
        // re-release fresh, even though the marker still exists.
        let dir2 = materialize_force_into(tmp.path()).expect("force extract");
        assert_eq!(dir2, dir, "same path");
        assert!(
            !dir2.join("stale-sentinel").exists(),
            "force extract must clear old files"
        );
        assert!(dir2.join(MARKER).exists(), "marker re-created");
        assert!(
            dir2.join("mr-guile-lsp/geiser/completion.scm").exists(),
            "deps re-extracted"
        );
    }
}
